format:
  class: Leankoala\HealthFoundation\Result\Format\Ietf\IetfFormat
  parameters:
    passedMessage: "Composer.lock has enough numbers of lines"
    failureMessage: "Composer.lock does not have enough numbers of lines"

checks:
  fileNumberOfLines:
    check: Leankoala\HealthFoundation\Check\Files\Content\NumberOfLinesCheck
    filter:
      nonStrict:
        decorator: Leankoala\HealthFoundation\Filter\Basic\NonStrictFilter
        parameters:
          maxErrorsInARow: 20
    identifier: composer_length
    description: 'Number of lines in the composer.lock file'
    parameters:
      file: composer.lock
      limit: 10
      relation: min
      pattern: 2019